#!/bin/bash

# Commented lines start with a #
#date
#cal
#pwd
#ls
#ps aux

# Here I set up some variables 
#var1=59
#var2=sheep
#var4=3
#fname=leon
#sname="R'obinson"

# Here I access the variables

#echo ${var1}
#echo ${var2}
#echo ${fname}
#echo ${sname}
#echo ${var3}
# Here I do a test

#if [ ${var1} -ne ${var4} ]
#then
#   echo The test returned true!  
#fi


# Test on USER name

if [ $USER = root ]
then
    echo "Hello Admin person"
else
    echo "You're not my admin"
fi




